---
- name: "Check and delete if old apr build directory exists"
  file: path=/usr/src/apr-devel state=absent

- name: "Copy source to server"
  copy: src=source/{{ apr_source_file }} dest=/usr/src

- name: "Extract source file"
  shell: 'mkdir /usr/src/apr-devel && tar -xzvf /usr/src/"{{ apr_source_file }}" -C /usr/src/apr-devel --strip-components=1'

- name: "Configure build and set environment"
  shell: 'chdir=/usr/src/apr-devel ./configure --prefix=/opt/libs'

- name: "Run make for apr"
  shell: 'chdir=/usr/src/apr-devel make'

- name: "Install apr"
  shell: 'chdir=/usr/src/apr-devel make install'
