---
- name: "Check and delete if old openssl build directory exists"
  file: path=/usr/src/tomcat-native state=absent

- name: "Copy source to server"
  copy: src=source/{{ tomcatnative_source_file }} dest=/usr/src

- name: "Extract source file"
  shell: 'mkdir /usr/src/tomcat-native && tar -xzvf /usr/src/"{{ tomcatnative_source_file }}" -C /usr/src/tomcat-native --strip-components=1'

- name: "Configure build and set environment"
  shell: 'chdir=/usr/src/tomcat-native/native ./configure --prefix=/opt/tomcat-native --with-java-home={{ java_home_dir }} --with-apr=/opt/libs --with-ssl=/opt/libs'

- name: "Run make for tomcat native"
  shell: 'chdir=/usr/src/tomcat-native/native make'

- name: "Install tomcat native"
  shell: 'chdir=/usr/src/tomcat-native/native make install'
